### PR TITLE
Redesigned about page and added CSS dependencies in Gemfile

### PR DESCRIPTION
**Pull request by Pancrisp**
### The whole site will be receiving a quick makeover for the presentation in JuniorDev on Thursday.

- Added CSS dependencies in our Gemfile and made a minor tweak to the Rails requirement.
- Redesigned our About page
- Fixed a bug with the profile links on the about page, was previously redirecting users to the GitHub API's JSON response.

### CODE REVIEW

**Review by thundergolfer — APPROVED** [review]

**Comment by Pancrisp** [comment]
Something simple to start with. The images are links that redirect to their respective GitHub profiles.

about-page

**Comment by Pancrisp** [comment]
Something simple to start with.

**Comment by thundergolfer** [comment]
My Github user icon is so dull here.

**Comment by thundergolfer** [comment]
@newmanicspree  @LouisKnuckles @Raddus Can someone do another review?

**Review by ghost — APPROVED** [review]

**Review by Louis-Stekhoven-Smith — APPROVED** [review]
👍  just need to fix the trivial merge conflict

**Comment by Pancrisp** [comment]
All done, should be good to merge @thundergolfer

**Comment by thundergolfer** [comment]
@Pancrisp It's your PR you should merge it now that you've got your 👍 s

**Pull request merged**
