### PR TITLE
[Trello - RZE78xkW] Basic network graph

### PR DESCRIPTION
**Pull request by thundergolfer**
### Description

This PR adds a copy-pasted *force-directed network graph* in **D3.js** that serves as a skeleton in which to pass our data. 

You can see that there's a `miserables.json` file, which was the [site's](https://bl.ocks.org/mbostock/4062045) example data. I've added some more realistic data in `organisation_connections.json`, which shows that once you have the data it's super easy to get a graph going. 

Our end product will basic end up passing in a javascript object that very much resembles `organisation_connections.json` to the `app/assets/javascripts/d3/network.js` file. Too easy.

#### What it currently looks like 

Because I couldn't be bother to type in a lot of data manually, it looks pretty bare. 

<kbd>
screen shot 2017-05-05 at 2 02 46 pm
</kbd>

### References

**Trello:** https://trello.com/c/RZE78xkW/28-setup-basic-network-graph-in-d3-js

### Risks

**None:** New route, new feature.

### CODE REVIEW

**Comment by thundergolfer** [comment]
```
Note: This PR has a deletion of `development.log`, because we've got to get 
that shit out of the repo. It's already in the .gitignore
```

**Comment by ghost** [comment]
Where's organisation_connections.json?

**Comment by thundergolfer** [comment]
@Raddus forgot to push my last commit. It's in there now.

**Comment by ghost** [comment]
Alright, looks good. But I don't really understand what the "group" and "value" numbers mean. I'll take a proper look at them later...

**Comment by thundergolfer** [comment]
In the case of the example `value` refers the number of times two characters appear in the same scene of Les Miserables. The higher this value, the *closer* the two nodes will be in the graph. 

In my data I just put in arbitrary stuff but the `value` should mean the number of times two members 'collaborated'. 

`group` is used to colour the nodes, but I don't know what their categorisation criteria is. I used I think: 

* 1 - Member of Org
* 2 - Prominent outside Github user (they're made up)
* 3 - Organisation

**Comment by thundergolfer** [comment]
I don't know whether we want this specific visualisation technique (closer means collab-ed more), but it's a good start. 

In future I think we just want the algorithm to nicely space out the nodes, and more collabs will show up in the visualisation as thicker edges and bigger (brighter) nodes.

**Review by ghost — APPROVED** [review]
Sorry it took so long, I thought I already reviewed it...

Looks good get merging.

**Review by Louis-Stekhoven-Smith — APPROVED** [review]
👍

**Pull request merged**
