### PR TITLE
Reworked authentication, it should now work with travis.

### PR DESCRIPTION
**Pull request by ghost**
# Description
This changes how we pass authentication information to the application. Instead of hard-coding, we can now use environment variables. 
This allows us to pass authentication information to Travis, _I think_, the builds appear to be passing. 
I am currently providing my encrypted info via .travis.yml (lines 12, 13), using a temporary password.
_This is a hacky solution until we get actual github auth._

# tl:dr
**Info passed to application using**
Rails.application.secrets.github_username
Rails.application.secrets.github_password
**Which is set in environment variables using**
export GITHUB_USERNAME="my_username" (OSX/Linux command)
export GITHUB_PASSWORD="my_password" (OSX/Linux command)
**Extra**
I'm not sure how to set environment variables on windows, if someone could let me know/test this it would be super helpful.

# References
How to pass encrypted environment variables to Travis
https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables

# Risks
- If someone can access your system they could view the environment variables you have set.
- This involves **secrets.yml**, I think we had a discussion about keeping it out of the repo? The only secrets it reveals are for development and testing environments, so it should be okay?
- Someone could decrypt my password (if they have a quantum computer or a time machine), but this is unlikely.

### CODE REVIEW

**Comment by thundergolfer** [comment]
Cool cool, I'll check this out in the morning.

**Comment by thundergolfer** [comment]
> If someone can access your system they could view the environment variables you have set.

Yep, but that's a wholly acceptable risk. Who can be arsed encrypting and decrypting their `.env` all the time.

**Review by thundergolfer — APPROVED** [review]

**Review by Pancrisp — APPROVED** [review]

**Comment by ghost** [comment]
Ahhhh man, I forgot to merge before I did some more stuff....
Is there some way to only merge up to a specific commit?
And I just noticed Erwin made a similar change......
I'll deal with this tomorrow -_-

**Comment by Pancrisp** [comment]
It should be fine, we'll just have to make some minor changes after the merge. Not that many conflicts beyond that since I was styling the about page (which you didn't, fortunately).

**Comment by thundergolfer** [comment]
@Raddus from what you've said the problem is, I think this should work. 

Create a new branch, that will contain all the work you did after getting your 👍s here. That branch should be made off the most recent `master`. 

`git log` this PR branch, and find the commits which are new. From the newly created branch `git cherry-pick` those new commits over. 

Now you've got those commits saved somewhere useful. It's alright to just do a `git reset --hard` to the last commit SHA that you actually want merged in this PR.

**Comment by thundergolfer** [comment]
@Pancrisp we should solve this without having to fix things *after* the merge. That's just a bit sloppy.

**Comment by Pancrisp** [comment]
@thundergolfer There's overlapping changes in the view templates. I can make the necessary changes before merging my PR though @Raddus has to merge this one first.

**Comment by ghost** [comment]
Problem solved?

**Comment by Pancrisp** [comment]
@Raddus Oop, you removed the markup and styling. Those can stay, I only made changes to the about page. Do you still have them?

**Comment by ghost** [comment]
@Pancrisp It's all good, I followed the advice from @thundergolfer and cherrypicked the changes to another branch (rad-bootstrap).

**Comment by thundergolfer** [comment]
@Pancrisp or @Raddus  if everything looks ok on `Integration` you're right to delete this branch.

**Pull request merged**
