### PR TITLE
Make the website pretty

### PR DESCRIPTION
**Pull request by ghost**
# Add Bootstrap v4 and refactor some views
Added gems to support Bootstrap
Split our aplication.html.erb into partials, for example we now have a header partial which is rendered on every page

## Notes
JONO: the graph css is now located in graph.scss

## Issues
I am having some issues with the svg's, I can't get them to center properly....

## Old welcome page 
old_welcome

## New welcome page
new_welcome

### CODE REVIEW

**Review by Pancrisp — APPROVED** [review]

**Comment by ghost** [comment]
@Pancrisp Slight issue, you removed font-awesome from the gemfile, so you should also remove `<%= fa_icon 'cog spin' %>` from: 
welcome.html.erb
2 `<h1 class="display-3">Work in progress <%= fa_icon 'cog spin' %></h1>`

**Comment by Pancrisp** [comment]
It's still there, I moved them towards the top of the Gemfile.

**Comment by ghost** [comment]
Oh, yep, didn't see it there -_-

**Comment by thundergolfer** [comment]
Can you put some screenshots in the PR description? Would be useful to see the improvements, and keep it as a record for tracking project regressions.

**Pull request merged**
